### ISSUE TITLE
Optional inputs broken

### ISSUE THREAD

**Issue by potash** [Factual/drake#161]
Optional inputs are not working for me (just recloned and rebuilt the uberjar). When I try the example from the manual 

    a_all <- ?does_not_exist [+skip-on-all]
        echo skip on all
    a_any <- does_not_exist [+skip-on-any]
        echo skip on any

I simply get:

    no input data found in locations: ?does_not_exist
        at drake.core$should_build_QMARK_.invoke(core.clj:204)
        at drake.core$predict_steps$fn__5192.invoke(core.clj:250)
        at clojure.core.protocols$fn__6089.invoke(protocols.clj:127)
        at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6080.invoke(protocols.clj:48)
        at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6289)
        at drake.core$predict_steps.invoke(core.clj:246)
        at drake.core$run.invoke(core.clj:618)
        at drake.core$drake$fn__5533.invoke(core.clj:851)
        at drake.core$with_workflow_file.invoke(core.clj:709)
        at drake.core$drake.doInvoke(core.clj:851)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:624)
        at drake.core$_main.doInvoke(core.clj:864)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at drake.core.main(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.flatland.drip.Main.invoke(Main.java:117)
        at org.flatland.drip.Main.start(Main.java:88)
        at org.flatland.drip.Main.main(Main.java:64)

**Comment by amalloy** [comment]
Where in the spec do you see how to use optional inputs? I don't see it anywhere, but I do see some comments in the source code to the effect that optional inputs are planned but not yet supported.

**Comment by dirtyvagabond** [comment]
There's a section called, "Optional inputs" (page 32 on my PDF download) which describes this. The section is properly coloured red though, to indicate "not implemented" as described in the colour key at the top of the spec.

Closing this as "won't fix ATM"

**Comment by potash** [comment]
Whoops, missed the color key. Thanks.
