### ISSUE TITLE
upgrade from 0.1.6 to 1.0.1 and S3 plugin broken?

### ISSUE THREAD

**Issue by danoyoung** [Factual/drake#192]
Hello,

Looking at upgrading to 1.0.1 from 0.1.6 and it looks like the S3 component is broken/changed???

foo.d:

x <- s3://my-coolio-bucket/temp/foo.txt [-timecheck] 
  aws s3 cp $INPUT -

[dan.young@silencer ~]$ drake --version
Drake Version 0.1.6 

[dan.young@silencer ~]$ drake --aws-credentials aws.properties --jobs=2 --workflow foo.d
The following steps will be run, in order:
  1: /home/dan.young/x <- s3://my-coolio-bucket/temp/foo.txt [missing output]
Confirm? [y/n] y
Running 1 steps with concurrence of 2...

--- 0. Running (missing output): /home/dan.young/x <- s3://my-coolio-bucket/temp/foo.txt
foo bar
--- 0: /home/dan.young/x <- s3://my-coolio-bucket/temp/foo.txt -> done in 0.38s
Done (1 steps run).

[etl@pixies000 ~]$ drake --version
Drake Version 1.0.1 

[etl@pixies000 ~]$ drake --aws-credentials aws.properties --jobs=2 --workflow foo.d 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/pool/ConnPoolControl
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at com.amazonaws.http.ConnectionManagerFactory.createPoolingClientConnManager(ConnectionManagerFactory.java:26)
	at com.amazonaws.http.HttpClientFactory.createHttpClient(HttpClientFactory.java:96)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:158)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:119)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:103)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:341)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:180)
	at aws.sdk.s3$s3_client_STAR_.invoke(s3.clj:78)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$memoize$fn__5097.doInvoke(core.clj:5846)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at aws.sdk.s3$get_object_metadata.doInvoke(s3.clj:392)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at aws.sdk.s3$object_exists_QMARK_.invoke(s3.clj:454)
	at drake.fs$fn__2467.invoke(fs.clj:277)
	at drake_interface.core$fn__1929$G__1879__1936.invoke(core.clj:8)
	at drake.fs$fn__2477.invoke(fs.clj:321)
	at drake_interface.core$fn__1996$G__1877__2003.invoke(core.clj:8)
	at drake.fs$data_in_QMARK__impl.invoke(fs.clj:64)
	at drake_interface.core$fn__1983$G__1875__1990.invoke(core.clj:8)
	at drake.fs$fs.invoke(fs.clj:443)
	at drake.parser$make_file_stats.invoke(parser.clj:320)
	at clojure.core$map$fn__4245.invoke(core.clj:2559)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$filter$fn__4264.invoke(core.clj:2595)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$map$fn__4245.invoke(core.clj:2551)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$empty_QMARK_.invoke(core.clj:5706)
	at drake.core$should_build_QMARK_.invoke(core.clj:225)
	at drake.core$predict_steps$fn__4871.invoke(core.clj:273)
	at clojure.core.protocols$fn__6089.invoke(protocols.clj:127)
	at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6080.invoke(protocols.clj:48)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at drake.core$predict_steps.invoke(core.clj:269)
	at drake.core$run.invoke(core.clj:654)
	at drake.core$drake$fn__5217.invoke(core.clj:890)
	at drake.core$with_workflow_file.invoke(core.clj:743)
	at drake.core$drake.doInvoke(core.clj:890)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:624)
	at drake.core$_main.doInvoke(core.clj:904)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at drake.core.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.http.pool.ConnPoolControl
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 74 more

Tried running foo.d like this too:

x <- !s3://my-coolio-bucket/temp/foo.txt [-timecheck] 
  aws s3 cp $INPUT -

**Comment by mavericklou** [comment]
This should be a dependency issue. It is true that ConnPoolControl is not in drake jar since 1.0.0. This class is in httpcore since version 4.2. When we removed google api and factql from c4, together we removed httpcore 4.2, then the highest version of httpcore in drake jar is 4.1.2 which is bring in by pomegranate. 

One thing weird is on Mac, I have no problem working with S3 using s3cmd.

**Comment by mavericklou** [comment]
Tried also on ubuntu
![image](https://cloud.githubusercontent.com/assets/855457/9121462/02f51b00-3cb5-11e5-8ea8-62209430ef07.png)

@danoyoung can't reproduce your problem

**Comment by danoyoung** [comment]
@mavericklou 

Tried this on an EC2 instance with the same result....



[dan.young@xxxx drake]$ ~/lein uberjar
Compiling drake.core
Compiling drake.stdin
Compiling drake.protocol-test
Compiling drake.shell
Compiling drake.clj-frontend
Compiling drake.clj-frontend-utils
Compiling drake.protocol
Compiling drake.plugins
Compiling drake.protocol-interpreters
Compiling drake.options
Compiling drake.protocol-c4
Compiling drake.viz
Compiling drake.protocol-eval
Compiling drake.event
Compiling drake.fs
Compiling drake.steps
Compiling drake.utils
Compiling drake.parser
Compiling drake.parser_utils
Created /home/dan.young/drake/target/drake-1.0.1.jar
Created /home/dan.young/drake/target/drake.jar
[dan.young@pixies drake]$ cd 
[dan.young@pixies ~]$ ls
aws.properties  drake  drake.log  foo.d  lein
[dan.young@pixies ~]$ which drake
/usr/local/bin/drake

[dan.young@xxx ~]$ java -cp drake/target/drake.jar drake.core --aws-credentials aws.properties --jobs=2 --workflow foo.d
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/pool/ConnPoolControl
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at com.amazonaws.http.ConnectionManagerFactory.createPoolingClientConnManager(ConnectionManagerFactory.java:26)
	at com.amazonaws.http.HttpClientFactory.createHttpClient(HttpClientFactory.java:96)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:158)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:119)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:103)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:341)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:180)
	at aws.sdk.s3$s3_client_STAR_.invoke(s3.clj:78)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:624)
	at clojure.core$memoize$fn__5097.doInvoke(core.clj:5846)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at aws.sdk.s3$get_object_metadata.doInvoke(s3.clj:392)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at aws.sdk.s3$object_exists_QMARK_.invoke(s3.clj:454)
	at drake.fs$fn__3335.invoke(fs.clj:277)
	at drake_interface.core$fn__1368$G__1318__1375.invoke(core.clj:8)
	at drake.fs$fn__3345.invoke(fs.clj:321)
	at drake_interface.core$fn__1435$G__1316__1442.invoke(core.clj:8)
	at drake.fs$data_in_QMARK__impl.invoke(fs.clj:64)
	at drake_interface.core$fn__1422$G__1314__1429.invoke(core.clj:8)
	at drake.fs$fs.invoke(fs.clj:443)
	at drake.parser$make_file_stats.invoke(parser.clj:320)
	at clojure.core$map$fn__4245.invoke(core.clj:2559)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$filter$fn__4264.invoke(core.clj:2595)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$map$fn__4245.invoke(core.clj:2551)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$empty_QMARK_.invoke(core.clj:5706)
	at drake.core$should_build_QMARK_.invoke(core.clj:225)
	at drake.core$predict_steps$fn__4731.invoke(core.clj:273)
	at clojure.core.protocols$fn__6089.invoke(protocols.clj:127)
	at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6080.invoke(protocols.clj:48)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at drake.core$predict_steps.invoke(core.clj:269)
	at drake.core$run.invoke(core.clj:654)
	at drake.core$drake$fn__5077.invoke(core.clj:890)
	at drake.core$with_workflow_file.invoke(core.clj:743)
	at drake.core$drake.doInvoke(core.clj:890)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:624)
	at drake.core$_main.doInvoke(core.clj:904)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at drake.core.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.http.pool.ConnPoolControl
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 74 more
[dan.young@xxx ~]$ 

[dan.young@xxx ~]$ java -cp drake/target/drake.jar drake.core --version
Drake Version 1.0.1 


[dan.young@xxx ~]$ uname -a
Linux xxx.xxx.net 3.14.35-28.38.amzn1.x86_64 #1 SMP Wed Mar 11 22:50:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mavericklou** [comment]
c60d03dfdb6d1986b7c52919e4aa0d3f5d0ffb7c

**Comment by danoyoung** [comment]
@mavericklou that worked!  thank you.

[dan.young@xxx ~]$ java -cp drake/target/drake.jar drake.core --aws-credentials aws.properties --jobs=2 --workflow foo.d
The following steps will be run, in order:
  1: /home/dan.young/x <- s3://xxx/temp/foo.txt [missing output]
Confirm? [y/n] y
Running 1 steps with concurrence of 2...

--- 0. Running (missing output): /home/dan.young/x <- s3://xxx/temp/foo.txt
foo bar
--- 0: /home/dan.young/x <- s3://craftsy-kafka/temp/foo.txt -> done in 0.35s
Done (1 steps run).

**Comment by mavericklou** [comment]
This is a dependency issue.
 [clj-aws-s3 "0.3.10" :exclusions [[joda-time]]]
   [com.amazonaws/aws-java-sdk "1.7.5"]
     [com.fasterxml.jackson.core/jackson-annotations "2.1.1"]
     [com.fasterxml.jackson.core/jackson-databind "2.1.1"]
     [org.apache.httpcomponents/httpclient "4.2"]
       [org.apache.httpcomponents/httpcore "4.2"]

org/apache/http/pool/ConnPoolControl this class only exists above 4.2 in httpcore. And it's been omit when conflict with com.cemerick/pomegranate "0.2.0".

The reason why we didn't found this issue in the first place is just because our pluggable support for different versions of hadoop clients. httpcore is such a common library that is easily enough to be spotted in big project like hadoop client. `hadoop classpath` is been introduced into drake run as long as hadoop client is installed. So, @danoyoung I am pretty sure that you don't have hadoop client installed. ;)

I've committed my fix to develop branch. @danoyoung I guess you can play with the latest code to solve your problem. We will release another maintenance release to make this fix formal.

**Comment by danoyoung** [comment]
correct, we do not have Hadoop installed.  Thank you.
