### ISSUE TITLE
Error in should-build?

### ISSUE THREAD

**Issue by chen-factual** [Factual/drake#194]
I've started seeing this error recently, I suspect it might have something to do with my optional file changes. I'll look into this.

Observed when some steps of the workflow have outputs, and some don't, running without specifying any steps / directives.

```
[main] ERROR drake.core - clojure.lang.ArityException: Wrong number of args (1) passed to: core/min-key
        at clojure.lang.AFn.throwArity(AFn.java:429)
        at clojure.lang.RestFn.invoke(RestFn.java:412)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:626)
        at drake.fs$pick_by_mod_time.invoke(fs.clj:472)
        at drake.fs$newest_in.invoke(fs.clj:480)
        at clojure.core$mapv$fn__6311.invoke(core.clj:6353)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
        at clojure.core.protocols$fn__6093.invoke(protocols.clj:98)
        at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
        at clojure.core.protocols$fn__6086.invoke(protocols.clj:147)
        at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6078.invoke(protocols.clj:54)
        at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6289)
        at clojure.core$mapv.invoke(core.clj:6353)
        at drake.core$should_build_QMARK_.invoke(core.clj:247)
        at drake.core$predict_steps$fn__208.invoke(core.clj:273)
        at clojure.core.protocols$fn__6089.invoke(protocols.clj:127)
        at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
        at clojure.core.protocols$fn__6080.invoke(protocols.clj:48)
        at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6289)
        at drake.core$predict_steps.invoke(core.clj:269)
        at drake.core$run.invoke(core.clj:654)
        at drake.core$drake$fn__554.invoke(core.clj:890)
        at drake.core$with_workflow_file.invoke(core.clj:743)
        at drake.core$drake.doInvoke(core.clj:890)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:624)
        at drake.core$_main.doInvoke(core.clj:904)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at drake.core.main(Unknown Source)
```

**Comment by chen-factual** [comment]
Snuck in a look at this while I'm waiting for a couple of things. This exception triggered during timestamp checking (newest input file newer than old input?) in ```should-build?```, while trying to find the newest file. 

Getting file-info for an optional file yields nothing because the file-seq in LocalFileSystem can't find the file with a "?" in front of it. I can patch this up by having ```existing-and-empty-inputs``` strip the "?" for existing inputs, so the rest of ```should-build?``` can treat them as regular files.

I think in the long term we should spread optional file awareness to basically the whole fs module (the most natural solution to me is to pass around a file object instead of a path string around). I won't have the time to take this on, but I just wanted you (@dirtyvagabond) to be aware this is something that maybe required if we keep seeing these issues pop up.

**Comment by amalloy** [comment]
I think it would be nice to have all of drake know about optional files, but not by making everything handle the strings with `?` in them: I'd like one initial step that translates `"/foo"` to `{:file "/foo" :optional false}` and `"?/foo"` to `{:file "/foo" :optional false}` (ideally using a File rather than the path string, as you say), and then the rest of drake can just deal with these tuple/struct objects. What do you guys think? Is this separation of concerns just too much effort for not enough benefit?

**Comment by amalloy** [comment]
Wait, it looks like that struct already exists, in `make-file-stats`. So that's nice. You're just campaigning for more functions accepting this struct instead of a filename? I agree, if so.

**Comment by chen-factual** [comment]
I was just about to link you to that function :)

Yeah, basically I'd advocating that should be the future path. I'm not saying it's needed now, I certainly didn't have any desire to add it when I was initially writing this feature. Currently, I don't think the effort is worth the benefit, but if we observe problems continuing to pop up we should move in this direction.

**Comment by chen-factual** [comment]
Fixed and merged.
