### ISSUE TITLE
ClassCastException when using a profile and a method(!)

### ISSUE THREAD

**Issue by potash** [Factual/drake#201]
I just upgraded to the newest version of drake and it is failing to interpret my workflow, throwing a ClassCastException. I narrowed it down to the existence of both a profile and a method:
```
PROFILE:=default_profile
%include $[PROFILE]

my_method()
    echo
```

If I remove one or the other, it works. But with both it breaks. The profile file itself can be empty so it's not related to the content of that. Below is the stacktrace.
 
```
$ drake
Using drip to start up JVM...
java.lang.ClassCastException: java.lang.Character cannot be cast to java.util.Map$Entry
        at clojure.lang.APersistentMap.cons(APersistentMap.java:42)
        at clojure.lang.RT.conj(RT.java:562)
        at clojure.core$conj.invoke(core.clj:83)
        at drake.parser$fn__3931$fn__3932$fn__3935$fn__3936$fn__3937$fn__3938$fn__3939$fn__3940$fn__3941$fn__3942$fn__3943.invoke(parser.clj:560)
        at clojure.algo.monads$update_val$fn__227.invoke(monads.clj:377)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374.invoke(monads.clj:585)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374$fn__375.invoke(monads.clj:585)
        at clojure.algo.monads$fn__181$m_bind_maybe__184.invoke(monads.clj:300)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374.invoke(monads.clj:585)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374$fn__375.invoke(monads.clj:585)
        at clojure.algo.monads$fn__181$m_bind_maybe__184.invoke(monads.clj:300)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374.invoke(monads.clj:585)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374$fn__375.invoke(monads.clj:585)
        at clojure.algo.monads$fn__181$m_bind_maybe__184.invoke(monads.clj:300)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374.invoke(monads.clj:585)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374$fn__375.invoke(monads.clj:585)
        at clojure.algo.monads$fn__181$m_bind_maybe__184.invoke(monads.clj:300)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374.invoke(monads.clj:585)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374$fn__375.invoke(monads.clj:585)
        at clojure.algo.monads$fn__181$m_bind_maybe__184.invoke(monads.clj:300)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374.invoke(monads.clj:585)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374$fn__375.invoke(monads.clj:585)
        at clojure.algo.monads$fn__181$m_bind_maybe__184.invoke(monads.clj:300)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374.invoke(monads.clj:585)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374$fn__375.invoke(monads.clj:585)
        at clojure.algo.monads$fn__181$m_bind_maybe__184.invoke(monads.clj:300)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374.invoke(monads.clj:585)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374$fn__375.invoke(monads.clj:585)
        at clojure.algo.monads$fn__181$m_bind_maybe__184.invoke(monads.clj:300)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374.invoke(monads.clj:585)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374$fn__375.invoke(monads.clj:585)
        at clojure.algo.monads$fn__181$m_bind_maybe__184.invoke(monads.clj:300)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374.invoke(monads.clj:585)
        at clojure.algo.monads$state_t$fn__381$fn__382$fn__383.invoke(monads.clj:596)
        at clojure.core$map$fn__4245.invoke(core.clj:2559)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$drop_while$step__4288.invoke(core.clj:2677)
        at clojure.core$drop_while$fn__4291.invoke(core.clj:2681)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.LazySeq.first(LazySeq.java:71)
        at clojure.lang.RT.first(RT.java:577)
        at clojure.core$first.invoke(core.clj:55)
        at clojure.algo.monads$fn__181$m_plus_maybe__186.doInvoke(monads.clj:302)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:624)
        at clojure.algo.monads$state_t$fn__381$fn__382.invoke(monads.clj:596)
        at drake.parser$fn__3996$fn__3997.invoke(parser.clj:612)
        at name.choi.joshua.fnparse$rep_STAR_$fn__449.invoke(fnparse.clj:265)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374.invoke(monads.clj:585)
        at clojure.algo.monads$state_t$m_bind_state_t__373$fn__374.invoke(monads.clj:585)
        at name.choi.joshua.fnparse$rule_match.invoke(fnparse.clj:430)
        at drake.parser$parse_state$fn__4074.invoke(parser.clj:716)
        at clojure.core$with_redefs_fn.invoke(core.clj:6861)
        at drake.parser$parse_state.invoke(parser.clj:713)
        at drake.parser$parse_str.invoke(parser.clj:731)
        at drake.parser$parse_file.invoke(parser.clj:736)
        at drake.core$with_workflow_file.invoke(core.clj:737)
        at drake.core$drake.doInvoke(core.clj:890)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)        at clojure.core$apply.invoke(core.clj:624)
        at drake.core$_main.doInvoke(core.clj:904)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at drake.core.main(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.flatland.drip.Main.invoke(Main.java:117)
        at org.flatland.drip.Main.start(Main.java:88)
        at org.flatland.drip.Main.main(Main.java:64)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
```

**Comment by potash** [comment]
The last (tagged) version with which this Drakefile worked was [v0.1.6](https://docs.google.com/uc?export=download&confirm=nT8F&id=0B2xtKcFEL6wwWnRzVzRZcGFFaWc)

If I switch the order of the profile call and the method definition:
```
my_method()
    echo

PROFILE:=default_profile
%include $[PROFILE]
```
drake doesn't error but as soon as I try to use the method:
```
my_method()
    echo

PROFILE:=default_profile
%include $[PROFILE]

output <- [method:my_method]
```
I get
```
drake: parse error at line 9, column 1: method 'my_method' undefined at this point.
```

**Comment by dirtyvagabond** [comment]
@amalloy you available to look at this?

**Comment by amalloy** [comment]
Yeah, I'll dig around. God `%include` is awful.

**Comment by amalloy** [comment]
To be clear, PROFILE isn't a drake-specific thing at all, right? it's just some variable you are setting in your drakefile?

**Comment by potash** [comment]
@amalloy That's right, it's just the path to my profile file. I followed the example on the [wiki](https://github.com/Factual/drake/wiki/Variables)

**Comment by amalloy** [comment]
Are you on the latest version? I can't reproduce locally, and I think this is the same issue as #187, which was fixed a while ago.

**Comment by amalloy** [comment]
I guess we haven't made any new releases since that commit, though. Time for 1.0.2 I guess.

**Comment by potash** [comment]
Oh, you're right looks like exactly the same issue. I really should've searched through existing issues.  Thanks for the quick response!

I am using 1.0.1 per the [script](https://raw.githubusercontent.com/Factual/drake/master/bin/drake). Is it possible to use HEAD via the script?

**Comment by amalloy** [comment]
No, I think you'd have to run from a source checkout. And we don't want to make you do that just to get a functioning tool. You can if you want, of course, but either way I think we should have 1.0.2 out pretty soon.

**Comment by potash** [comment]
Cool, looking forward to it since I'm currently on an ancient version.
